name: CI-GenericCardReaderFriend

# Controls when the workflow will run
on:
    # Trigger the workflow on push or pull request events
    push:
    pull_request:
    # Allow to run this workflow manually from the Actions tab
    workflow_dispatch:
    # Run the workflow for published releases
    release:
        types: [published]

env:
  PROJECT_TYPE: KEXT

jobs:
  # Build the kext
  build:
    name: Build
    runs-on: macos-13
    permissions:
     contents: write
    env:
      JOB_TYPE: BUILD
    steps:
     # Checkout the card reader repo
      - uses: actions/checkout@v5
     # Checkout the MacKernelSDK repo
      - uses: actions/checkout@v5
        with:
          repository: acidanthera/MacKernelSDK
          path: MacKernelSDK
      - name: CI Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1
      - name: Lilu Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1
      # Build the driver
      - run: xcodebuild -jobs 1 -configuration Debug
      - run: xcodebuild -jobs 1 -configuration Release
      # Upload the driver
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: Artifacts
          path: build/*/*.zip
      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.11.2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*/*.zip
          tag: ${{ github.ref }}
          file_glob: true
